### ISSUE TITLE
Unable to clone/fetch/push due to TransportException

### ISSUE THREAD

**Issue by jdjamsa1** [ajoberstar/grgit#150] opened 2017-03-10 20:58 UTC
Is there a way to avoid errors such as this?

```
org.ajoberstar.grgit.exception.GrgitException: Problem fetching from remote.

	at org.ajoberstar.grgit.operation.FetchOp.call(FetchOp.groovy:100)
	at org.ajoberstar.grgit.util.OpSyntaxUtil.tryOp(OpSyntaxUtil.groovy:45)
	at org.ajoberstar.grgit.Grgit.methodMissing(Grgit.groovy:188)
	at com.optum.jjamsa.GrgitSpec.test open(GrgitSpec.groovy:81)
Caused by: org.eclipse.jgit.api.errors.TransportException: https://me@myserver/myrepo.git: 302 Found
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:134)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:76)
	at org.ajoberstar.grgit.operation.FetchOp.call(FetchOp.groovy:97)
	... 3 more
Caused by: org.eclipse.jgit.errors.TransportException:  https://me@myserver/myrepo.git: 302 Found
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:502)
	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:288)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1179)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:128)
	... 5 more
```

**Comment by ajoberstar** [comment] 2017-03-11 00:32
It appears this might be a [JGit limitation](https://bugs.eclipse.org/bugs/show_bug.cgi?id=389617). You might be stuck if there's not a way to avoid getting a 302 response from your git server.

**Comment by ajoberstar** [comment] 2017-10-22 20:42
JGit marked that bug as a duplicate of [this](https://bugs.eclipse.org/bugs/show_bug.cgi?id=465167) which has been resolved for some time. If you are still seeing this issue, please reopen.

**Closed by ajoberstar** 2017-10-22 20:42 UTC
Labels: blocked:jgit
