### ISSUE TITLE
release 2.2.0 is broken

### ISSUE THREAD

**Issue by mtsahakis** [ajoberstar/grgit#234] opened 2018-06-01 07:43 UTC
Hi,

I know that there is a lot of effort going on into publishing 2.2.1 release.

Somehow though latest stable 2.2.0 is being broken for some time. My setup is the following:

buildscript {
    ext {
        springBootVersion = '2.0.1.RELEASE'
    }
    repositories {
        jcenter()
        mavenCentral()
        maven { url "https://plugins.gradle.org/m2/" }
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        classpath("com.github.amkay:gradle-gitflow:0.2.0")
        classpath("org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:2.6.2")
        classpath("org.ajoberstar:grgit:2.2.0")
    }
}

plugins {
    id 'org.unbroken-dome.test-sets' version '1.4.2'
    id 'org.sonarqube' version '2.6.2'
    id 'org.ajoberstar.grgit' version '2.2.0'
}

The error I am getting is:

No signature of method: org.eclipse.jgit.internal.storage.file.FileRepository.getRef() is applicable for argument types: (java.lang.String) values: [HEAD]
     Possible solutions: getAt(java.lang.String), getFS(), grep(), exactRef(java.lang.String), findRef(java.lang.String), getAllRefs()

The workaround was to switch to 2.2.1-rc4 published in gradle plugin portal.

Looking forward to 2.2.1, good luck.

Regards,

Manos

**Comment by wwn** [comment] 2018-06-01 08:10
It's caused by indside dependency to eclipse with open range. Eclipse relased yesterday.

**Comment by mtsahakis** [comment] 2018-06-01 08:18
Hope 2.2.1 goes out soon! For the time being I switched my builds to 2.2.1-rc.4

**Comment by wwn** [comment] 2018-06-01 08:42
We currently solved it with update gradle wrapper from 4.6 to 4.7

**Comment by ajoberstar** [comment] 2018-06-01 11:32
I'm going to close this as a duplicate of #229.

I intended to release 2.2.1 final yesterday, but realized my other plugins that depend on grgit had the same problem. I wanted to make sure I got a working rc out for all of them.

Final release will come out tonight.

**Closed by ajoberstar** 2018-06-01 11:32 UTC

**Comment by mtsahakis** [comment] 2018-06-01 12:54
I can confirm that gradle wrapper 4.7 fixes the issue for us.
