### ISSUE TITLE
Older versions of Java (e.g. 8 and 9) are no longer compatible after recent JGit 6 update

### ISSUE THREAD

**Issue by Crunkle** [ajoberstar/grgit#341] opened 2021-11-30 00:23 UTC
The plugin on Gradle's repository (currently 4.1.0) targets the latest release of JGit and does not abide by the dependency locks. JGit 6 was released today making Java 11 a requirement and, as a result, the latest published plugin no longer works on older versions of Java. It appears that the latest working version is 4.0.2 which directly targets JGit 5.x rather than latest.

```xml
<artifactId>grgit-core</artifactId>
<version>4.1.0</version>
<dependencies>
  <dependency>
    <groupId>org.eclipse.jgit</groupId>
    <artifactId>org.eclipse.jgit</artifactId>
    <version>RELEASE</version>
    <scope>compile</scope>
  </dependency>
</dependencies>
```

```xml
<artifactId>grgit-core</artifactId>
<version>4.0.2</version>
<dependencies>
  <dependency>
    <groupId>org.eclipse.jgit</groupId>
    <artifactId>org.eclipse.jgit</artifactId>
    <version>5.7.0.202003110725-r</version>
    <scope>compile</scope>
  </dependency>
</dependencies>
```

To preserve backwards compatibility, could we fix the dependency versions and target JGit 5.9 instead?

**Comment by fritaly** [comment] 2021-11-30 06:54
This change started affecting a lot of builds in my company and I suspect that we are not alone. Releasing a "4.1.1" with a pinned down version would probably do the trick.

**Comment by jjoslet** [comment] 2021-11-30 10:33
You must probably use locked version to generate the POM instead of Gradle declared version. See https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:resolved_dependencies.

A workaround for user is to fix the jgit dependency in the pom.xml:
```
<dependency>
	<groupId>org.eclipse.jgit</groupId>
	<artifactId>org.eclipse.jgit</artifactId>
	<version>5.9.0.202009080501-r</version>
</dependency>
```

**Comment by cadonna** [comment] 2021-11-30 12:46
Same issue in the Apache Kafka project when you build from scratch without any local dependencies for gradle.

**Comment by rybak** [comment] 2021-11-30 14:23
For convenience, here are all relevant links to code of GrGit.

Overall tag comparison: https://github.com/ajoberstar/grgit/compare/4.0.2...4.1.0

Dependency locking for JGit:

* 4.0.2 for `org.eclipse.jgit:org.eclipse.jgit:5.7.0.202003110725-r`: https://github.com/ajoberstar/grgit/blob/4.0.2/grgit-core/gradle/dependency-locks/runtimeClasspath.lockfile#L10
* 4.1.0 for `org.eclipse.jgit:org.eclipse.jgit:5.9.0.202009080501-r`: https://github.com/ajoberstar/grgit/blob/4.1.0/grgit-core/gradle/dependency-locks/runtimeClasspath.lockfile#L5

Dependency declaration:
```groovy
  // jgit
  api 'org.eclipse.jgit:org.eclipse.jgit:latest.release'
```
* 4.0.2: https://github.com/ajoberstar/grgit/blob/4.0.2/grgit-core/build.gradle#L17-L18
* 4.1.0: https://github.com/ajoberstar/grgit/blob/4.1.0/grgit-core/build.gradle#L18-L19

**Comment by AlexanderStohr** [comment] 2021-11-30 15:21
in principle same is reported for mkDocs plugin:
https://github.com/xvik/gradle-mkdocs-plugin/issues/13

**Comment by ArvinB** [comment] 2021-11-30 15:51
So luckily...my plugin code was reworked earlier this year to be compatible with Java 11 even though I was on Java 8. Ran into this exact same issue after 11.25.2021 and the solution for us was to simply update our Java runtime from 8 to 11 on the Jenkins build system.

There are a lot of security updates with Java 11, where performing a hotfix to downgrade `grgit` to `4.0.2` may not be the best solution. I would suggest instead revisiting any code that is not compatible with Java 11 and fix that. It's most likely the use of some deprecated APIs.

FYI @diazarturo

**Comment by AlexanderStohr** [comment] 2021-11-30 15:53
> You must probably use locked version to generate the POM instead of Gradle declared version. See https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:resolved_dependencies.
> 
> A workaround for user is to fix the jgit dependency in the pom.xml:
> 
> ```
> <dependency>
> 	<groupId>org.eclipse.jgit</groupId>
> 	<artifactId>org.eclipse.jgit</artifactId>
> 	<version>5.9.0.202009080501-r</version>
> </dependency>
> ```

here i had even more recent builds working nice for me (this year, September):
    org.eclipse.jgit/5.13.0.202109080827-r

**Comment by ajoberstar** [comment] 2021-11-30 19:38
Duplicate of #339

**Closed by ajoberstar** 2021-11-30 19:38 UTC

**Comment by AlexanderStohr** [comment] 2021-12-01 09:49
now works for me with latest grgit 4.1.1
