### ISSUE TITLE
2.x not available in Maven Central

### ISSUE THREAD

**Issue by szpak** [ajoberstar/grgit#196] opened 2017-09-17 13:45 UTC
Upgrading from 1.7 to 2.0.1 I have noticed that 2.x versions are [no longer available](https://repo1.maven.org/maven2/org/ajoberstar/grgit/) in Maven Central. I would prefer to not rely on jcenter just for that library (especially that in Gradle it is not possible to define that jcenter should be only used for the one particular dependency). Could you put newer version of the library also to Maven Central (e.g. using Bintray's [synchronization mechanism](https://bintray.com/docs/usermanual/uploads/uploads_syncingwiththirdpartyplatforms.html#_syncing_artifacts_with_maven_central))?

**Comment by ajoberstar** [comment] 2017-09-17 20:24
Main reason is all of the extra requirements Central has. Not ruling it out it's just low priority for me.

Duplicate of #175.

**Closed by ajoberstar** 2017-09-17 20:24 UTC

**Comment by ajoberstar** [comment] 2017-09-17 23:10
Well, the sync and PGP gets handled by Bintray, but the rest is on the user. I believe the missing pieces are the POM additions and the call to the Bintray sync.

The Bintray plugin has always been frustrating to me, as it relies on bad Gradle practices to work (largely afterEvaluate). It makes it difficult to get other plugins or build logic to work well with it. I dropped their plugin and now use the out of the box maven-publish one instead to get to Bintray.

This does mean I miss out on their other features, like automating the call to their Bintray sync.

Ultimately, I want to keep a one step release process and didn't feel deploying to Central was worth the extra work.

**Comment by ajoberstar** [comment] 2017-09-17 23:13
Other piece being that I maintain a handful of projects and want a consistent process for all of them too. I've tried to avoid situations where I have to customize a single project. Not opposed to Maven Central, so if you have ideas or want to contribute let's discuss more.
