### ISSUE TITLE
jgit suddenly sees an incompatible update in my build setup

### ISSUE THREAD

**Issue by alexanderLinear** [ajoberstar/grgit#342] opened 2021-11-30 13:59 UTC
this ticket is meant to be sort of a reference for people running in a similar problem.
its about using grgit-core-4.1.0.pom (and grgit-gradle in same version) for a specific project setup with many fixed versions.

after this version your package went over to using latest release of jgit.
https://github.com/ajoberstar/grgit/blob/9313853863c7139f1f6f444f81ad3d0c4bb348d8/grgit-core/build.gradle

when using it in such a still current form i suddenly got an update of jgit and related packages from
    org.eclipse.jgit/5.13.0.202109080827-r
to
    org.eclipse.jgit/6.0.0.202111291000-r

this resulted to me in build errors like this:
    java.lang.UnsupportedClassVersionError: org/eclipse/jgit/api/Git has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
this effectively means that i "wanted" to use Java 8 but got a package from jgit that was fixed to Java 11 only.

i am now looking after some method for patching in a hard, fixed version like i had previously to resolve my builds. i will probably do a little fork from the version i were incorporating already and then use the old coding style as linked above. some suffix might be enough to distinguish and select this dependency adapted variant. as its only about configuration values of an alpha-numerical sort i feel like its not tampering with the core of codes or the solution itself, so i feel its not a thing needed to be released on its own for e.g. licensing sakes. anyways i feel like it would be of minor to no use to the public for now. (unless someone finds that to be a problem of a much more general scale and nature.)

**Comment by nicolasblaye** [comment] 2021-11-30 14:14
same issue here, would be interested in the fix if you make it. I will try to make something too since this is blocking for us but it seems you understand it better than me

**Comment by nicolasblaye** [comment] 2021-11-30 14:21
same issue as https://github.com/ajoberstar/grgit/issues/341

**Comment by AlexanderStohr** [comment] 2021-11-30 15:21
in principle same is reported for mkDocs plugin:
https://github.com/xvik/gradle-mkdocs-plugin/issues/13

**Comment by AlexanderStohr** [comment] 2021-11-30 16:11
grgit already received an interesting PR along with a bit of feedback on how to solve it best.
https://github.com/ajoberstar/grgit/pull/340

**Comment by ajoberstar** [comment] 2021-11-30 19:38
Duplicate of #339

**Closed by ajoberstar** 2021-11-30 19:38 UTC
